package com.dws.isobarfm.infrastructure.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/** OpenAPI metadata; the spec and Swagger UI are generated by springdoc. */
@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI isobarFmOpenApi() {
        return new OpenAPI().info(new Info()
                .title("isobar.fm API")
                .description("Bands and albums, backed by the DWS bands-api with a caching layer.")
                .version("1.0.0"));
    }
}
